In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6,7])
print(a)
print(type(a))

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>


In [3]:
a = [10,20,30,40]
b = np.array(a)
print(b)

[10 20 30 40]


In [4]:
a = (1,2,3,4,5,6)
b = np.array(a)
print(b)

[1 2 3 4 5 6]


In [5]:
a = np.array([[10,20,30],[40,50,60]])
print(a)

[[10 20 30]
 [40 50 60]]


In [7]:
a = np.array([[[10,20,30,40,50]]])
print(a)
print(a.ndim)

[[[10 20 30 40 50]]]
3


In [8]:
a = np.array(100)
b = np.array([11,22,33,44])
c = np.array([[10,20,30],[40,50,60]])
d = np.array([[[100,200,300,400]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [9]:
a = np.array([11,22,33,44,55,66,77])
print(a)


[11 22 33 44 55 66 77]


In [10]:
print(a[0])

11


In [11]:
print(a[-3])

55


In [12]:
a = np.array([[10,20,30],[40,50,60]])
print(a)

[[10 20 30]
 [40 50 60]]


In [13]:
a = np.array([[[10,20,30,40]]])
print(a)

[[[10 20 30 40]]]


In [16]:
a[0][0][1]

20

In [17]:
a[0][0][2]

30

In [18]:
a = np.array([[11,22,33,44]])
print(a)


[[11 22 33 44]]


In [19]:
print(a[0][2])

33


In [20]:
a = np.array([[1,2,3,4,5,6,7]])
print(a)

[[1 2 3 4 5 6 7]]


In [21]:
a = np.array([[[10,20,30,40,50]]])
print(a)

[[[10 20 30 40 50]]]


In [22]:
print(a[0][0][3])

40


In [23]:
print(a[0,0,2])

30


In [24]:
a = np.array([[11,22,33],[44,55,66]])
print(a)

[[11 22 33]
 [44 55 66]]


In [25]:
a[0][0]

11

In [27]:
a[0][1]

22

In [29]:
a[0,0]

11

In [30]:
a = np.array([[1,2,3,4,5]], ndmin = 5)
print(a)

[[[[[1 2 3 4 5]]]]]


In [31]:
a = np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [34]:
print(a[0:2])

[1 2]


In [35]:
print(a[-3:-1])

[4 5]


In [36]:
print(a[:3])

[1 2 3]


In [37]:
a = np.array([[10,20,30],[40,50,60]])
print(a)

[[10 20 30]
 [40 50 60]]


In [41]:
print(a[0:1,0:2])
print(a[1:2,0:2])

[[10 20]]
[[40 50]]


In [42]:
print(a[-3:-1])

[[10 20 30]]


In [43]:
print(a[1,2])

60


In [44]:
print(a[1,1:3])

[50 60]


In [45]:
print(a[0,0:2])

[10 20]


In [46]:
a = np.array([[[1,2,3,4,5],[6,7,8,9,10]]])
print(a)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]]


In [47]:
print(a[0:1,0:2])

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]]


In [56]:
print(a[0:2,1:3,1:2])
print(a[0:2,0:3,1:2])

[[[7]]]
[[[2]
  [7]]]


In [58]:
a = np.array([10,20,30,40,50,60])
print(a)

[10 20 30 40 50 60]


In [59]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [60]:
print(a[0:1,0:2])

[[1 2]]


In [61]:
a = np.array([10,20,30])
print(a)
print(a.dtype)

[10 20 30]
int32


In [62]:
a = np.array([[1.1,2.2],[3.3,4.4]])
print(a)
print(a.dtype)

[[1.1 2.2]
 [3.3 4.4]]
float64


In [63]:
a = np.array([[[True,False]]])
print(a)
print(a.dtype)

[[[ True False]]]
bool


In [67]:
a = np.array([[1+2J,3+4J],[5+4J,6+7J]])
print(a)
print(a.dtype)

[[1.+2.j 3.+4.j]
 [5.+4.j 6.+7.j]]
complex128


In [68]:
a = np.array([['aa','bb','dd','ee','ff']])
print(a)
print(a.dtype)

[['aa' 'bb' 'dd' 'ee' 'ff']]
<U2


In [69]:
a = np.array([10,20,30,40], dtype = 'float')
print(a)

[10. 20. 30. 40.]


In [70]:
a = np.array([[1.1,2.2,3.3,4.4]], dtype='int')
print(a)

[[1 2 3 4]]


In [73]:
a = np.array([[['1','2','3','4','5']]], dtype = 'int64')
print(a)
print(a.dtype)

[[[1 2 3 4 5]]]
int64


In [75]:
a = np.array([1,2,3,4,5,0])
b = a.astype('bool')
print(b)

[ True  True  True  True  True False]


In [76]:
a = np.array([['1','2','3','4']])
b = a.astype('int')
print(b)

[[1 2 3 4]]


In [77]:
a = np.array([[10,20,30,40,50,60]])
print(a)
b = a.copy()
print(b)
b[0,0]=100
print(a)
print(b)

[[10 20 30 40 50 60]]
[[10 20 30 40 50 60]]
[[10 20 30 40 50 60]]
[[100  20  30  40  50  60]]


In [78]:
a = np.array([1,2,3,4,5,6,7,8])
b = a.view()
b[0]=10
print(a)
print(b)

[10  2  3  4  5  6  7  8]
[10  2  3  4  5  6  7  8]


In [79]:
a = np.array([[11,22,33,44]])
b = a.copy()
c = a.view()
print(b.base)
print(c.base)

None
[[11 22 33 44]]


In [80]:
a = np.array([100,200,300,400,500])
for x in a:
    print(x)

100
200
300
400
500


In [81]:
a = np.array([[1,2,3,4,5,6,7,8]])
for i in a:
    print(i)


[1 2 3 4 5 6 7 8]


In [82]:
a = np.array([[[1,2,3,4,5,6,7,8]]])
for x in a:
    print(x)
    for y in x:
        print(y)
        for z in y:
            print(z)

[[1 2 3 4 5 6 7 8]]
[1 2 3 4 5 6 7 8]
1
2
3
4
5
6
7
8


In [83]:
a = np.array([[1,2,3,4,5,6,7,8]])
b = a.reshape(4,2,1)
print(b)

[[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]

 [[7]
  [8]]]


In [84]:
a = np.array([[[1,2,3,4,5]]])
b = a.reshape(5,-1)
print(b)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [85]:
a = np.array([[[[1,2,3,4,5,6]]]])
b = a.reshape(-1)
print(b)

[1 2 3 4 5 6]


In [88]:
a = np.array([[[10,20],[30,40]],[[50,60],[70,80]]])
for x in np.nditer(a):
    print(x)
    

10
20
30
40
50
60
70
80


In [89]:
a = np.array([[1,2,3],[4,5,6]])
b = np.nditer(a)
for x in b:
    print(x)

1
2
3
4
5
6


In [90]:
a = np.array([[10,20,30,40,50,60]])
for i in np.nditer(a, flags = ['buffered'], op_dtypes = ['S']):
    print(i)

b'10'
b'20'
b'30'
b'40'
b'50'
b'60'


In [91]:
a = np.array([[['1','2','3','4','5']]])
for i in np.nditer(a, flags=['buffered'], op_dtypes = ['U']):
    print(i)

1
2
3
4
5


In [92]:
a = np.array([[10,20,30,40,50,60]])
for i in np.nditer(a[0,0:2]):
    print(i)

10
20


In [93]:
a = np.array([[[10,20],[30,40]],[[50,60],[70,80]]])
for i in np.ndenumerate(a):
    print(i)

((0, 0, 0), 10)
((0, 0, 1), 20)
((0, 1, 0), 30)
((0, 1, 1), 40)
((1, 0, 0), 50)
((1, 0, 1), 60)
((1, 1, 0), 70)
((1, 1, 1), 80)


In [94]:
a = np.array([[1,2,34,5]])
for i in np.ndenumerate(a):
    print(i)

((0, 0), 1)
((0, 1), 2)
((0, 2), 34)
((0, 3), 5)


In [95]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.concatenate((a,b))
print(c)

[1 2 3 4 5 6]


In [98]:
a = np.array([[10,20,30,40]])
b = np.array([[50,60,70,80]])
c = np.concatenate((a,b),axis=1)
print(c)

[[10 20 30 40 50 60 70 80]]


In [99]:
a = np.array([[1,2,3]])
b = np.array([[4,5,6]])
c = np.stack((a,b))
print(c)

[[[1 2 3]]

 [[4 5 6]]]


In [100]:
a = np.array([[[10,20,30]]])
b = np.array([[[40,50,60]]])
c = np.stack((a,b), axis=1)
print(c)

[[[[10 20 30]]

  [[40 50 60]]]]


In [101]:
a = np.array([[11,22,33]])
b = np.array([[44,55,66]])
c = np.hstack((a,b))
print(c)

[[11 22 33 44 55 66]]


In [104]:
a = np.array([[[10,20,30]]])
b = np.array([[[40,50,60]]])
c = np.hstack((a,b))
print(c)

[[[10 20 30]
  [40 50 60]]]


In [111]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.vstack((a,b))
print(c)

[[1 2 3]
 [4 5 6]]


In [109]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.stack((a,b))
print(c)

[[1 2 3]
 [4 5 6]]


In [112]:
a = np.array([[10,20,30]])
b = np.array([[40,50,60]])
c = np.hstack((a,b))
print(c)

[[10 20 30 40 50 60]]


In [113]:
a = np.array([[[1,2,3,4]]])
b = np.array([[[5,6,7,8]]])
c = np.hstack((a,b))
print(c)

[[[1 2 3 4]
  [5 6 7 8]]]


In [114]:
a = np.array([[100,200]])
b = np.array([[300,400]])
c = np.dstack((a,b))
print(c)

[[[100 300]
  [200 400]]]


In [115]:
a = np.array([1,2])
b = np.array([3,4])
c = np.dstack((a,b))
print(c)

[[[1 3]
  [2 4]]]


In [116]:
a = np.array([1,2,3,4,5,6,7,8])
b = np.split(a,2)
print(b)

[array([1, 2, 3, 4]), array([5, 6, 7, 8])]


In [118]:
a = np.array([[1,2,3,4],[5,6,7,8]])
b = np.split(a,2,axis=1)
print(b)

[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


In [122]:
a = np.array([[[1,2,3,4],[5,6,7,8]]])
b = np.split(a,2,axis=1)
print(b)

[array([[[1, 2, 3, 4]]]), array([[[5, 6, 7, 8]]])]


In [124]:
a = np.array([[11,22,33,44],[55,66,77,88]])
b = np.array_split(a,2)
print(b)
for i in b:
    print(i)

[array([[11, 22, 33, 44]]), array([[55, 66, 77, 88]])]
[[11 22 33 44]]
[[55 66 77 88]]


In [130]:
a = np.array([[100,200],[300,400]])
print(a.shape)
b = np.array_split(a,2,axis=1)
print(b)

for i in b:
    print(i)

(2, 2)
[array([[100],
       [300]]), array([[200],
       [400]])]
[[100]
 [300]]
[[200]
 [400]]


In [131]:
a = np.array([[1,2,3,4,5,6]])
b = np.hsplit(a,2)
print(b)

[array([[1, 2, 3]]), array([[4, 5, 6]])]


In [134]:
a = np.array([[[10,20,30,40,50,60]]])
b = np.vsplit(a,1)
print(b)
for i in 

[array([[[10, 20, 30, 40, 50, 60]]])]


In [137]:
a = np.array([[1,2,3,4],[5,6,7,8]])
b = np.vsplit(a,2)
print(b)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]


In [140]:
a = np.array([[[11,22,33,44],[55,66,77,88]]])
b = np.hsplit(a,2)
print(b)

[array([[[11, 22, 33, 44]]]), array([[[55, 66, 77, 88]]])]


In [144]:
a = np.array([[[1,2,3,4],[5,6,7,8]]])
b = np.dsplit(a,2)
print(b)

[array([[[1, 2],
        [5, 6]]]), array([[[3, 4],
        [7, 8]]])]


In [145]:
a = np.array([[1,2,3,4,5]])
b = np.where(a==2)
print(b)

(array([0], dtype=int64), array([1], dtype=int64))


In [148]:
a = np.array([[[10,20],[30,40]],[[50,60],[70,80]]])
b = np.where(a%2==0)
print(b)

(array([0, 0, 0, 0, 1, 1, 1, 1], dtype=int64), array([0, 0, 1, 1, 0, 0, 1, 1], dtype=int64), array([0, 1, 0, 1, 0, 1, 0, 1], dtype=int64))


In [149]:
a = np.array([[[1,2,3,4,5,6,7,8,9]]])
b = np.where(a==4)
print(b)

(array([0], dtype=int64), array([0], dtype=int64), array([3], dtype=int64))


In [153]:
a = np.array([[10,20,30],[40,50,60]])
print(a)
print(a+1)
print(a-1)
print(a*5)

[[10 20 30]
 [40 50 60]]
[[11 21 31]
 [41 51 61]]
[[ 9 19 29]
 [39 49 59]]
[[ 50 100 150]
 [200 250 300]]


In [154]:
a = np.array([1,2,3,4,5,6,7,8,9])
b = np.searchsorted(a,4)
print(b)

3


In [155]:
a = np.array([10,20,30,40,50,60])
b = np.searchsorted(a,40,side='right')
print(b)

4


In [156]:
a= np.array([11,22,33,44])
b = np.searchsorted(a,20,side='left')
print(b)

1


In [158]:
a = np.array([1,2,3,4,5,6,7])
b = np.searchsorted(a,1,side='right')
print(b)

1


In [159]:
a = np.array([[1,5,4,6,7,3,2]])
b = np.sort(a)
print(b)

[[1 2 3 4 5 6 7]]


In [161]:
a = np.array([['bb','ss','aa','cc','dd']])
b = np.sort(a)
print(b)

[['aa' 'bb' 'cc' 'dd' 'ss']]


In [162]:
a = np.array([[True,False,True]])
b = np.sort(a)
print(b)

[[False  True  True]]


In [163]:
a = np.array([[3,0,2,1]])
b = np.sort(a)
print(b)

[[0 1 2 3]]


In [167]:
a = np.array([[55,44,33,22,11]])
b = np.sort(a,axis=1)
print(b)

[[11 22 33 44 55]]


In [168]:
a = np.array([[1,2,3,4,5]])
b = np.sort(a,axis=1)
print(b)

[[1 2 3 4 5]]


In [171]:
a = np.array([[[2,1,3],[4,7,6]]])
b = np.sort(a,axis=-1)
print(b)

[[[1 2 3]
  [4 6 7]]]


In [175]:
a = np.array([[1,2,3,4,5,6,7]])
b = [[True,False,True,False,True,False,True]]
c = a[b]
print(c)

[1 3 5 7]


In [178]:
a = np.array([1,2,3,4])
b = [True,False,False,True]
c = a[b]
print(c)

[1 4]


In [180]:
a = np.array([1,2,3,4,5,6,7])
b = np.searchsorted(a,[1,2,4])
print(b)

[0 1 3]


In [181]:
a = np.array([[1,2],[3,4]])
b = [[True,False],[False,True]]
c = a[b]
print(c)

[1 4]


In [183]:
a = np.array([100,200,300,400,500,600])
print(a)
index =[]
for i in a:
    print(i)
    if i<20:
        index.append(True)
    else:
        index.append(False)
print(index)
b = a[index]
print(b)

[100 200 300 400 500 600]
100
200
300
400
500
600
[False, False, False, False, False, False]
[]


In [185]:
a = np.array([10,20,30,40,50,60])
print(a)
index =[]
for i in a:
    print(i)
    if i<22:
        index.append(True)
    else:
        index.append(False)
print(index)
b = a[index]
print(b)

[10 20 30 40 50 60]
10
20
30
40
50
60
[True, True, False, False, False, False]
[10 20]


In [186]:
a = np.array([11,12,13,14,15,16,17,18])
print(a)
index=[]
for i in a:
    print(i)
    if i%2==1:
        index.append(True)
    else:
        index.append(False)
print(index)
b = a[index]
print(b)

[11 12 13 14 15 16 17 18]
11
12
13
14
15
16
17
18
[True, False, True, False, True, False, True, False]
[11 13 15 17]


In [195]:
a = np.arange(20)
print(a)
print(type(a))
print(a.min())
print(a.max())
print(a.argmin())
print(a.argmax())
print(a.sum())
print(a.mean())
print(a.nonzero())
b = a.reshape(10,2,1)
print(b)
print(b.diagonal())
print(b.ravel())


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
<class 'numpy.ndarray'>
0
19
0
19
190
9.5
(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19], dtype=int64),)
[[[ 0]
  [ 1]]

 [[ 2]
  [ 3]]

 [[ 4]
  [ 5]]

 [[ 6]
  [ 7]]

 [[ 8]
  [ 9]]

 [[10]
  [11]]

 [[12]
  [13]]

 [[14]
  [15]]

 [[16]
  [17]]

 [[18]
  [19]]]
[[0 3]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [198]:
a = np.linspace(10,2)
print(a)


[10.          9.83673469  9.67346939  9.51020408  9.34693878  9.18367347
  9.02040816  8.85714286  8.69387755  8.53061224  8.36734694  8.20408163
  8.04081633  7.87755102  7.71428571  7.55102041  7.3877551   7.2244898
  7.06122449  6.89795918  6.73469388  6.57142857  6.40816327  6.24489796
  6.08163265  5.91836735  5.75510204  5.59183673  5.42857143  5.26530612
  5.10204082  4.93877551  4.7755102   4.6122449   4.44897959  4.28571429
  4.12244898  3.95918367  3.79591837  3.63265306  3.46938776  3.30612245
  3.14285714  2.97959184  2.81632653  2.65306122  2.48979592  2.32653061
  2.16326531  2.        ]


In [199]:
a = np.random.randn(10,2,1)
print(a)

[[[ 0.45952839]
  [ 2.14708473]]

 [[-1.96666298]
  [-1.57195954]]

 [[-0.80540558]
  [-0.17655183]]

 [[-0.83331329]
  [ 0.54882694]]

 [[ 0.42131972]
  [-0.94076644]]

 [[-0.56880114]
  [ 1.20676885]]

 [[ 0.10022148]
  [ 0.27403374]]

 [[-0.29214777]
  [ 1.65018409]]

 [[-1.60348075]
  [-0.45285943]]

 [[ 0.07964512]
  [-1.2105347 ]]]


In [201]:
a=np.eye(5,2)
print(a)

[[1. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [202]:
a = np.ones((2,5,1))
print(a)

[[[1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]
  [1.]]]


In [204]:
a = np.diag([5,2])
print(a)

[[5 0]
 [0 2]]


In [207]:
a = np.linspace(20,10,1)
print(a)

[20.]


In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5,6,7])
print(a)
print(type(a))
for i in a:
    print(i)

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>
1
2
3
4
5
6
7


In [4]:
a = [[10,20,30,40],[50,60,70,80]]
b = np.array(a)
print(b)

[[10 20 30 40]
 [50 60 70 80]]


In [6]:
a = np.array ([[[11,22,33,44,55,66,77]]])
print(a)
for i in a:
    print(i)

[[[11 22 33 44 55 66 77]]]
[[11 22 33 44 55 66 77]]


In [8]:
a = np.array(10)
b = np.array([10,20,30])
c = np.array([[11,22,33,44]])
d = np.array([[[100,200,300,400,500]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [9]:
a = np.array([10,20,30,40], ndmin = 5)
print(a)

[[[[[10 20 30 40]]]]]


In [12]:
a = (10,20,30)
b = np.array(a)
print(b)
print(b.ndim)

[10 20 30]
1


In [13]:
b[0]

10

In [14]:
b[[0,1]]

array([10, 20])

In [16]:
a = [1,2,3,4],[5,6,7,8]
b = np.array(a)
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [24]:
b[0]
print(b[1])
print(b[0,2])
print(b[0,1])
print(b[0:1,0:3])
print(b[1:,0:2])

[5 6 7 8]
3
2
[[1 2 3]]
[[5 6]]


In [25]:
a = [[[1,2,3,4],[5,6,7,8]]]
b = np.array(a)
print(b)

[[[1 2 3 4]
  [5 6 7 8]]]


In [46]:
print(b[0])
print(b[0,0,1])
print(b[0:1,0:1,0:2])
print(b[0][0][2])
print(b[0][1][2])
print(b[:10:2])
print(b[::4])
print(b[0:1:2])
print(b[0,1:3,2])

[[1 2 3 4]
 [5 6 7 8]]
2
[[[1 2]]]
3
7
[[[1 2 3 4]
  [5 6 7 8]]]
[[[1 2 3 4]
  [5 6 7 8]]]
[[[1 2 3 4]
  [5 6 7 8]]]
[7]


In [47]:
a = np.array([1,2,3,4,5,6])
print(a)
print(a.dtype)

[1 2 3 4 5 6]
int32


In [48]:
a = np.array([1.1,2.2,3.3,4.4])
print(a)
print(a.dtype)

[1.1 2.2 3.3 4.4]
float64


In [49]:
a = np.array([True, False])
print(a)
print(a.dtype)

[ True False]
bool


In [50]:
a = np.array([1,2,3,4,5], dtype = 'float')
print(a)
print(a.dtype)

[1. 2. 3. 4. 5.]
float64


In [51]:
a = np.array(['aa','bb','cc','dd'])
print(a)
print(a.dtype)

['aa' 'bb' 'cc' 'dd']
<U2


In [53]:
a = np.array([11,22,33,44], dtype = 'U')
print(a)
print(a.dtype)

['11' '22' '33' '44']
<U2


In [54]:
a = np.array([1,2,3,4,5])
b = a.astype('float')
print(b)

[1. 2. 3. 4. 5.]


In [58]:
a = np.array([1+2j,3+4j,5+6j,0+0j])
b = a.astype('bool')
print(b)

[ True  True  True False]


In [59]:
a = np.array([1,0,2])
b = a.astype('complex')
print(b)

[1.+0.j 0.+0.j 2.+0.j]


In [60]:
a = np.array([10,20,30,40])
print(a)
b = a.copy()
b[0]=100
print(a)
print(b)

[10 20 30 40]
[10 20 30 40]
[100  20  30  40]


In [61]:
a = np.array([[1,2,3,4,5,6]])
b = a.view()
b[0,1]=200
print(a)
print(b)

[[  1 200   3   4   5   6]]
[[  1 200   3   4   5   6]]


In [62]:
a = np.array([1,2,3,4,5,6])
print(a)
b = a.copy()
c = a.view()
print(b.base)
print(c.base)

[1 2 3 4 5 6]
None
[1 2 3 4 5 6]


In [63]:
a = np.array([1,2,3,4,5,6,7,8])
b = a.reshape(4,2,1)
print(b)

[[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]

 [[7]
  [8]]]


In [64]:
a = np.array([[1,2,3,4,5,6,7,8]])
b = a.reshape(4,2,-1)
print(b)

[[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]

 [[7]
  [8]]]


In [65]:
a = np.array([[[1,2,3,4,5]]])
b = a.reshape(-1)
print(b)

[1 2 3 4 5]


In [66]:
a = np.array([1,2,3,4,5,6])
for i in a:
    print(i)

1
2
3
4
5
6


In [67]:
a = np.array([[10,20,30,40,50]])
for i in np.nditer(a):
    print(i)

10
20
30
40
50


In [71]:
a = np.array([[[1,2,3,4,5,6,7,8]]])
for i in np.nditer(a, flags = ['buffered'], op_dtypes = ['S']):
    print(i)

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'


In [70]:
a = np.array(['11','22','33','44'])
for i in np.nditer(a, flags = ['buffered'], op_dtypes = ['U']):
    print(i)

11
22
33
44


In [72]:
a = np.array([[1,2,3,4],[5,6,7,8]])
for i in np.nditer(a[0:1]):
    print(i)

1
2
3
4


In [73]:
a = np.array([[1,2,3,4,5,6,7]])
for i in np.ndenumerate(a):
    print(i)

((0, 0), 1)
((0, 1), 2)
((0, 2), 3)
((0, 3), 4)
((0, 4), 5)
((0, 5), 6)
((0, 6), 7)


In [74]:
print(a[0][0])

1


In [80]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.concatenate((a,b), axis =0)
print(c)

[1 2 3 4 5 6]


In [78]:
a = np.array([10,20,30])
b = np.array([40,50,60])
c = np.stack((a,b), axis = 1)
print(c)

[[10 40]
 [20 50]
 [30 60]]


In [84]:
a = np.array([[11,22,33]])
b = np.array([[44,55,66]])
c = np.hstack(a)
print(c)

[11 22 33]


In [85]:
a = np.array([[11,22,33]])
b = np.array([[44,55,66]])
c = np.vstack(a)
print(c)

[[11 22 33]]


In [86]:
a = np.array([[11,22,33]])
b = np.array([[44,55,66]])
c = np.dstack(a)
print(c)

[[[11]
  [22]
  [33]]]


In [89]:
a = np.array([1,2,3,4,5,6,7,8])
b = np.split(a,2)
print(b)

[array([1, 2, 3, 4]), array([5, 6, 7, 8])]


In [94]:
a = np.array([[[10,20,30,40],[50,60,70,80]]])
b = np.split(a,1,axis=1)
b
for i in b:
    print(i)

[[[10 20 30 40]
  [50 60 70 80]]]


In [95]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array_split(a,2)
b

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [96]:
b[0]

array([[1, 2, 3]])

In [97]:
b[1]

array([[4, 5, 6]])

In [98]:
a = np.array([[1,2,3,4],[5,6,7,8]])
b = np.array_split(a,2,axis=1)
print(b)

[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


In [100]:
a = np.array([1,2,3,4,5,6])
b = np.hsplit(a,2)
b

[array([1, 2, 3]), array([4, 5, 6])]

In [103]:
a = np.array([[11,22,33,44,55,66]])
b = np.vsplit(a,1)
b

[array([[11, 22, 33, 44, 55, 66]])]

In [105]:
a = np.array([[[1,2,3,4],[5,6,7,8]]])
b = np.dsplit(a,2)
b

[array([[[1, 2],
         [5, 6]]]),
 array([[[3, 4],
         [7, 8]]])]

In [106]:
a = np.array([3,2,4,1,5,6])
b = np.where(a==4)
b

(array([2], dtype=int64),)

In [107]:
a = np.array([[[10,20,30],[50,40,60]]])
b = np.where(a%2==0)
b

(array([0, 0, 0, 0, 0, 0], dtype=int64),
 array([0, 0, 0, 1, 1, 1], dtype=int64),
 array([0, 1, 2, 0, 1, 2], dtype=int64))

In [113]:
a = np.array([[1,2,3,4,5,6,7,8]])
print(a)
print(a+2)
print(a*5)
print(a/5)
print(a%2)
print(a**3)

[[1 2 3 4 5 6 7 8]]
[[ 3  4  5  6  7  8  9 10]]
[[ 5 10 15 20 25 30 35 40]]
[[0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6]]
[[1 0 1 0 1 0 1 0]]
[[  1   8  27  64 125 216 343 512]]


In [114]:
a = np.array([1,2,3,4,5,6])
b = np.searchsorted(a,4)
b


3

In [115]:
a = np.array([10,20,30,40,50])
b = np.searchsorted(a, 20, side = 'right')
b

2

In [116]:
a = np.array([10,20,30,40,50,60,70,80])
b = np.searchsorted(a,[20,40,60])
b

array([1, 3, 5], dtype=int64)

In [117]:
a = np.array([[11,22,55,66,44,33]])
b = np.sort(a)
b

array([[11, 22, 33, 44, 55, 66]])

In [120]:
a = np.array([[[1,3,2],[6,5,4]]])
b = np.sort(a, axis=2)
b

array([[[1, 2, 3],
        [4, 5, 6]]])

In [121]:
a = np.array(['rr','gg','aa','bb','ee'])
b = np.sort(a)
b


array(['aa', 'bb', 'ee', 'gg', 'rr'], dtype='<U2')

In [122]:
a = np.array([True, False])
b = np.sort(a)
b

array([False,  True])

In [124]:
a = np.array([1,2,3])
b = [True, False, True]
c = a[b]
c

array([1, 3])

In [126]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(a)
index = []
for i in a:
    print(i)
    if i<15:
        index.append(True)
    else:
        index.append(False)
print(index)
b = a[index]
print(b)

[1 2 3 4 5 6 7 8 9]
1
2
3
4
5
6
7
8
9
[True, True, True, True, True, True, True, True, True]
[1 2 3 4 5 6 7 8 9]


In [128]:
a = np.array([11,22,33,44,55,66])
print(a)
index = []
for i in a:
    print(i)
    if i%2==1:
        index.append(True)
    else:
        index.append(False)
print(index)
b = a[index]
b

[11 22 33 44 55 66]
11
22
33
44
55
66
[True, False, True, False, True, False]


array([11, 33, 55])

In [129]:
a = np.arange(20)
print(a)
print(type(a))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
<class 'numpy.ndarray'>


In [130]:
a = np.arange(40)
b = a.reshape(8,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [131]:
a = np.arange(30)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [141]:
print(a.min())
print(a.max())
print(a.argmin())
print(a.argmax())
print(a.sum())
print(a.mean())
b = a.reshape(6,5)
print(b)
print(b.diagonal())
print(b.ravel())

0
29
0
29
435
14.5
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
[ 0  6 12 18 24]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [142]:
a = np.random.randn(6,5)
a

array([[ 0.04186017,  1.03737106,  1.27811504,  1.94800831,  1.20808901],
       [-2.00897668, -0.57131697,  0.26479254,  2.04012685,  1.24184141],
       [-1.35724218, -0.25493393, -0.29101606, -1.2703914 ,  0.23595431],
       [ 1.38417706,  0.73923342,  0.70872766,  0.7809341 ,  0.01994063],
       [-0.58777525,  0.94903584,  0.2876058 , -0.97625449,  0.38459088],
       [ 1.5169285 , -0.41328182, -0.16201897,  1.51066112, -2.54857442]])

In [144]:
print(a.argsort())

[[0 1 4 2 3]
 [0 1 2 4 3]
 [0 3 2 1 4]
 [4 2 1 3 0]
 [3 0 2 4 1]
 [4 1 2 3 0]]


In [145]:
print(a.nonzero())

(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4,
       4, 4, 4, 5, 5, 5, 5, 5], dtype=int64), array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1,
       2, 3, 4, 0, 1, 2, 3, 4], dtype=int64))


In [146]:
a = np.linspace(6,5)
print(a)

[6.         5.97959184 5.95918367 5.93877551 5.91836735 5.89795918
 5.87755102 5.85714286 5.83673469 5.81632653 5.79591837 5.7755102
 5.75510204 5.73469388 5.71428571 5.69387755 5.67346939 5.65306122
 5.63265306 5.6122449  5.59183673 5.57142857 5.55102041 5.53061224
 5.51020408 5.48979592 5.46938776 5.44897959 5.42857143 5.40816327
 5.3877551  5.36734694 5.34693878 5.32653061 5.30612245 5.28571429
 5.26530612 5.24489796 5.2244898  5.20408163 5.18367347 5.16326531
 5.14285714 5.12244898 5.10204082 5.08163265 5.06122449 5.04081633
 5.02040816 5.        ]


In [148]:
a = np.eye(6,5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [150]:
a=np.ones((6,5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [152]:
a = np.diag([6,5])
a

array([[6, 0],
       [0, 5]])